-- Create products table
CREATE TABLE if not exists products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    stock_quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL
);

-- Create orders table
CREATE TABLE if not exists  orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    paid_at TIMESTAMP,
    canceled_at TIMESTAMP
);

-- Create order_items table
CREATE TABLE if not exists  order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    price_per_unit DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Create indexes
CREATE INDEX if not exists  idx_orders_status ON orders(status);
CREATE INDEX if not exists  idx_orders_expires_at ON orders(expires_at);
CREATE INDEX if not exists  idx_order_items_order_id ON order_items(order_id);
CREATE INDEX if not exists  idx_order_items_product_id ON order_items(product_id);
