ALTER TABLE orders ADD order_number VARCHAR NOT NULL;
ALTER TABLE orders ADD order_items VARCHAR DEFAULT '[]';
ALTER TABLE orders ALTER COLUMN CREATED_AT TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ALTER COLUMN EXPIRES_AT TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN UPDATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders DROP COLUMN PAID_AT;
ALTER TABLE orders DROP COLUMN CANCELED_AT;

UPDATE orders SET order_number = 'LEGACY-' + id;

ALTER TABLE orders ADD CONSTRAINT uk_orders_order_number UNIQUE (order_number);

DROP TABLE order_items;
